// Code generated by MockGen. DO NOT EDIT.
// Source: yandex_gophermart/internal/app/handlers (interfaces: StorageInt,JWTHelperInt)

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	context "context"
	reflect "reflect"
	entities "yandex_gophermart/pkg/entities"

	gomock "github.com/golang/mock/gomock"
)

// MockStorageInt is a mock of StorageInt interface.
type MockStorageInt struct {
	ctrl     *gomock.Controller
	recorder *MockStorageIntMockRecorder
}

// MockStorageIntMockRecorder is the mock recorder for MockStorageInt.
type MockStorageIntMockRecorder struct {
	mock *MockStorageInt
}

// NewMockStorageInt creates a new mock instance.
func NewMockStorageInt(ctrl *gomock.Controller) *MockStorageInt {
	mock := &MockStorageInt{ctrl: ctrl}
	mock.recorder = &MockStorageIntMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageInt) EXPECT() *MockStorageIntMockRecorder {
	return m.recorder
}

// AddRoBalance mocks base method.
func (m *MockStorageInt) AddRoBalance(arg0 int, arg1 float64, arg2 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoBalance", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoBalance indicates an expected call of AddRoBalance.
func (mr *MockStorageIntMockRecorder) AddRoBalance(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoBalance", reflect.TypeOf((*MockStorageInt)(nil).AddRoBalance), arg0, arg1, arg2)
}

// CheckUser mocks base method.
func (m *MockStorageInt) CheckUser(arg0, arg1 string, arg2 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUser indicates an expected call of CheckUser.
func (mr *MockStorageIntMockRecorder) CheckUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUser", reflect.TypeOf((*MockStorageInt)(nil).CheckUser), arg0, arg1, arg2)
}

// GetBalance mocks base method.
func (m *MockStorageInt) GetBalance(arg0 int, arg1 context.Context) (entities.BalanceData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", arg0, arg1)
	ret0, _ := ret[0].(entities.BalanceData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockStorageIntMockRecorder) GetBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockStorageInt)(nil).GetBalance), arg0, arg1)
}

// GetOrdersList mocks base method.
func (m *MockStorageInt) GetOrdersList(arg0 int, arg1 context.Context) ([]entities.OrderData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersList", arg0, arg1)
	ret0, _ := ret[0].([]entities.OrderData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersList indicates an expected call of GetOrdersList.
func (mr *MockStorageIntMockRecorder) GetOrdersList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersList", reflect.TypeOf((*MockStorageInt)(nil).GetOrdersList), arg0, arg1)
}

// GetWithdrawals mocks base method.
func (m *MockStorageInt) GetWithdrawals(arg0 int, arg1 context.Context) ([]entities.WithdrawalData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", arg0, arg1)
	ret0, _ := ret[0].([]entities.WithdrawalData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockStorageIntMockRecorder) GetWithdrawals(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockStorageInt)(nil).GetWithdrawals), arg0, arg1)
}

// SaveNewOrder mocks base method.
func (m *MockStorageInt) SaveNewOrder(arg0 entities.OrderData, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNewOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveNewOrder indicates an expected call of SaveNewOrder.
func (mr *MockStorageIntMockRecorder) SaveNewOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNewOrder", reflect.TypeOf((*MockStorageInt)(nil).SaveNewOrder), arg0, arg1)
}

// SaveUser mocks base method.
func (m *MockStorageInt) SaveUser(arg0, arg1 string, arg2 context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockStorageIntMockRecorder) SaveUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockStorageInt)(nil).SaveUser), arg0, arg1, arg2)
}

// UpdateOrder mocks base method.
func (m *MockStorageInt) UpdateOrder(arg0 entities.OrderData, arg1 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOrder", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOrder indicates an expected call of UpdateOrder.
func (mr *MockStorageIntMockRecorder) UpdateOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrder", reflect.TypeOf((*MockStorageInt)(nil).UpdateOrder), arg0, arg1)
}

// WithdrawFromBalance mocks base method.
func (m *MockStorageInt) WithdrawFromBalance(arg0, arg1 int, arg2 float64, arg3 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithdrawFromBalance", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithdrawFromBalance indicates an expected call of WithdrawFromBalance.
func (mr *MockStorageIntMockRecorder) WithdrawFromBalance(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithdrawFromBalance", reflect.TypeOf((*MockStorageInt)(nil).WithdrawFromBalance), arg0, arg1, arg2, arg3)
}

// MockJWTHelperInt is a mock of JWTHelperInt interface.
type MockJWTHelperInt struct {
	ctrl     *gomock.Controller
	recorder *MockJWTHelperIntMockRecorder
}

// MockJWTHelperIntMockRecorder is the mock recorder for MockJWTHelperInt.
type MockJWTHelperIntMockRecorder struct {
	mock *MockJWTHelperInt
}

// NewMockJWTHelperInt creates a new mock instance.
func NewMockJWTHelperInt(ctrl *gomock.Controller) *MockJWTHelperInt {
	mock := &MockJWTHelperInt{ctrl: ctrl}
	mock.recorder = &MockJWTHelperIntMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTHelperInt) EXPECT() *MockJWTHelperIntMockRecorder {
	return m.recorder
}

// BuildNewJWTString mocks base method.
func (m *MockJWTHelperInt) BuildNewJWTString(arg0 int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildNewJWTString", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildNewJWTString indicates an expected call of BuildNewJWTString.
func (mr *MockJWTHelperIntMockRecorder) BuildNewJWTString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildNewJWTString", reflect.TypeOf((*MockJWTHelperInt)(nil).BuildNewJWTString), arg0)
}

// GetUserID mocks base method.
func (m *MockJWTHelperInt) GetUserID(arg0 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockJWTHelperIntMockRecorder) GetUserID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockJWTHelperInt)(nil).GetUserID), arg0)
}
